name: Deploy to Staging - TangoTiempo BackEnd

on:
  push:
    branches:
      - STAGE
  pull_request:
    branches:
      - STAGE
    types: [opened, synchronize, reopened] # Only trigger on specific pull request events

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Node.js environment
      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Checkout the code
      - name: "Checkout code"
        uses: actions/checkout@v3

      # Install dependencies
      - name: "Install dependencies"
        run: npm install

      # Wait to avoid conflicts
      - name: "Wait for ongoing deployments"
        run: sleep 15

      # Deploy to Azure WebApp (Staging)
      - name: "Deploy to Azure WebApp (Staging)"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "tangotiempoprodbe" # Directly specified
          slot-name: "stage" # Directly specified
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_011CCAE104BA49F5B1163B7F994DA2BC }}

      # Health check to verify deployment (optional)
      - name: "Verify deployment"
        run: |
          curl -f -s https://tangotiempoprodbe-stage.azurewebsites.net/ || exit 1
